/**
 * CalculiX Input File (.inp) Writer
 * Generates CalculiX input files from simulation setup
 */

import {
  FEAMesh,
  FEAMaterial,
  FEAMaterialAssignment,
  BoundaryCondition,
  FixedConstraint,
  DisplacementConstraint,
  ForceLoad,
  PressureLoad,
  GravityLoad,
  SimulationSetup,
  StaticAnalysisSettings,
  ModalAnalysisSettings,
} from '@feai/shared';

export class InpWriter {
  private lines: string[] = [];

  /**
   * Generate complete CalculiX input file
   */
  generateInputFile(setup: SimulationSetup): string {
    this.lines = [];

    // Header
    this.writeHeader(setup);

    // Nodes
    if (setup.mesh) {
      this.writeNodes(setup.mesh);
      this.writeElements(setup.mesh);
      this.writeNodeSets(setup.mesh);
      this.writeElementSets(setup.mesh);
    }

    // Materials
    this.writeMaterials(setup.materials);

    // Solid sections (material assignments)
    this.writeSolidSections(setup.materialAssignments, setup.mesh);

    // Analysis step
    this.writeAnalysisStep(setup);

    return this.lines.join('\n');
  }

  private writeHeader(setup: SimulationSetup): void {
    this.lines.push('*HEADING');
    this.lines.push(`${setup.name} - Generated by feai FEA Module`);
    this.lines.push(`Analysis Type: ${setup.analysisType}`);
    this.lines.push(`Generated: ${new Date().toISOString()}`);
    this.lines.push('**');
    this.lines.push('** ==============================================================');
    this.lines.push('** MODEL DEFINITION');
    this.lines.push('** ==============================================================');
    this.lines.push('**');
  }

  private writeNodes(mesh: FEAMesh): void {
    this.lines.push('**');
    this.lines.push('** NODES');
    this.lines.push('**');
    this.lines.push('*NODE');

    for (const node of mesh.nodes) {
      // Format: node_id, x, y, z
      this.lines.push(
        `${node.id}, ${node.x.toExponential(8)}, ${node.y.toExponential(8)}, ${node.z.toExponential(8)}`
      );
    }
  }

  private writeElements(mesh: FEAMesh): void {
    this.lines.push('**');
    this.lines.push('** ELEMENTS');
    this.lines.push('**');

    // Group elements by type
    const elementsByType = new Map<string, typeof mesh.elements>();
    for (const element of mesh.elements) {
      const existing = elementsByType.get(element.type) || [];
      existing.push(element);
      elementsByType.set(element.type, existing);
    }

    // Write each element type group
    for (const [type, elements] of elementsByType) {
      this.lines.push(`*ELEMENT, TYPE=${type}, ELSET=E${type}`);
      for (const element of elements) {
        // Format: element_id, node1, node2, node3, ...
        const nodeList = element.nodeIds.join(', ');
        this.lines.push(`${element.id}, ${nodeList}`);
      }
    }
  }

  private writeNodeSets(mesh: FEAMesh): void {
    if (mesh.nodeSets.length === 0) return;

    this.lines.push('**');
    this.lines.push('** NODE SETS');
    this.lines.push('**');

    for (const nset of mesh.nodeSets) {
      this.lines.push(`*NSET, NSET=${nset.name}`);
      // Write nodes in groups of 16 per line
      const nodeIds = [...nset.nodeIds];
      while (nodeIds.length > 0) {
        const chunk = nodeIds.splice(0, 16);
        this.lines.push(chunk.join(', ') + (nodeIds.length > 0 ? ',' : ''));
      }
    }
  }

  private writeElementSets(mesh: FEAMesh): void {
    if (mesh.elementSets.length === 0) return;

    this.lines.push('**');
    this.lines.push('** ELEMENT SETS');
    this.lines.push('**');

    for (const eset of mesh.elementSets) {
      this.lines.push(`*ELSET, ELSET=${eset.name}`);
      const elementIds = [...eset.elementIds];
      while (elementIds.length > 0) {
        const chunk = elementIds.splice(0, 16);
        this.lines.push(chunk.join(', ') + (elementIds.length > 0 ? ',' : ''));
      }
    }
  }

  private writeMaterials(materials: FEAMaterial[]): void {
    this.lines.push('**');
    this.lines.push('** MATERIALS');
    this.lines.push('**');

    for (const material of materials) {
      const props = material.properties;

      this.lines.push(`*MATERIAL, NAME=${this.sanitizeName(material.name)}`);

      // Elastic properties (required)
      this.lines.push('*ELASTIC');
      this.lines.push(`${props.youngsModulus.toExponential(8)}, ${props.poissonsRatio}`);

      // Density (optional but commonly needed)
      if (props.density && props.density > 0) {
        this.lines.push('*DENSITY');
        this.lines.push(`${props.density.toExponential(8)}`);
      }

      // Thermal conductivity (for thermal analysis)
      if (props.thermalConductivity && props.thermalConductivity > 0) {
        this.lines.push('*CONDUCTIVITY');
        this.lines.push(`${props.thermalConductivity.toExponential(8)}`);
      }

      // Specific heat (for transient thermal)
      if (props.specificHeat && props.specificHeat > 0) {
        this.lines.push('*SPECIFIC HEAT');
        this.lines.push(`${props.specificHeat.toExponential(8)}`);
      }

      // Thermal expansion (for thermal stress)
      if (props.thermalExpansion && props.thermalExpansion > 0) {
        this.lines.push('*EXPANSION');
        this.lines.push(`${props.thermalExpansion.toExponential(8)}`);
      }
    }
  }

  private writeSolidSections(
    assignments: FEAMaterialAssignment[],
    mesh: FEAMesh | undefined
  ): void {
    this.lines.push('**');
    this.lines.push('** SOLID SECTIONS');
    this.lines.push('**');

    if (assignments.length === 0 && mesh) {
      // Default: assign first material to all elements
      this.lines.push('*SOLID SECTION, ELSET=Eall, MATERIAL=Steel');
      return;
    }

    for (const assignment of assignments) {
      // Use element set for this part if available, otherwise use Eall
      const elset = `Eall`; // In production, would map part -> element set
      const matName = this.sanitizeName(assignment.materialName);
      this.lines.push(`*SOLID SECTION, ELSET=${elset}, MATERIAL=${matName}`);
    }
  }

  private writeAnalysisStep(setup: SimulationSetup): void {
    this.lines.push('**');
    this.lines.push('** ==============================================================');
    this.lines.push('** ANALYSIS STEP');
    this.lines.push('** ==============================================================');
    this.lines.push('**');

    switch (setup.analysisType) {
      case 'static':
        this.writeStaticStep(setup);
        break;
      case 'modal':
        this.writeModalStep(setup);
        break;
      default:
        this.writeStaticStep(setup);
    }
  }

  private writeStaticStep(setup: SimulationSetup): void {
    this.lines.push('*STEP');
    this.lines.push('*STATIC');
    // Can add: initial_time_increment, total_time, min_increment, max_increment
    // this.lines.push('1., 1., 1e-5, 1.');

    // Boundary conditions
    this.writeBoundaryConditions(setup.boundaryConditions, setup.mesh);

    // Output requests
    this.writeOutputRequests();

    this.lines.push('*END STEP');
  }

  private writeModalStep(setup: SimulationSetup): void {
    const settings = setup.modalSettings || { numModes: 10 };

    this.lines.push('*STEP');
    this.lines.push('*FREQUENCY');
    this.lines.push(`${settings.numModes}`);

    // Boundary conditions (constraints only, no loads for modal)
    const constraints = setup.boundaryConditions.filter(
      (bc) => bc.type === 'fixed' || bc.type === 'displacement'
    );
    this.writeBoundaryConditions(constraints, setup.mesh);

    // Output requests for mode shapes
    this.lines.push('*NODE FILE');
    this.lines.push('U');
    this.lines.push('*EL FILE');
    this.lines.push('S');

    this.lines.push('*END STEP');
  }

  private writeBoundaryConditions(
    bcs: BoundaryCondition[],
    mesh: FEAMesh | undefined
  ): void {
    const constraints: BoundaryCondition[] = [];
    const loads: BoundaryCondition[] = [];

    // Separate constraints and loads
    for (const bc of bcs) {
      if (!bc.enabled) continue;

      if (bc.type === 'fixed' || bc.type === 'displacement') {
        constraints.push(bc);
      } else {
        loads.push(bc);
      }
    }

    // Write boundary constraints
    if (constraints.length > 0) {
      this.lines.push('**');
      this.lines.push('** BOUNDARY CONDITIONS');
      this.lines.push('**');
      this.lines.push('*BOUNDARY');

      for (const bc of constraints) {
        this.writeConstraint(bc, mesh);
      }
    }

    // Write loads
    if (loads.length > 0) {
      this.lines.push('**');
      this.lines.push('** LOADS');
      this.lines.push('**');

      for (const bc of loads) {
        this.writeLoad(bc, mesh);
      }
    }
  }

  private writeConstraint(bc: BoundaryCondition, mesh: FEAMesh | undefined): void {
    if (bc.type === 'fixed') {
      const fixed = bc as FixedConstraint;
      // Fixed in all 3 DOFs (1-3 for translations)
      // Format: node_set or node_id, first_dof, last_dof, value
      const nodeSetName = this.getNodeSetName(fixed.geometry, mesh);
      this.lines.push(`${nodeSetName}, 1, 3, 0.0`);
    } else if (bc.type === 'displacement') {
      const disp = bc as DisplacementConstraint;
      const nodeSetName = this.getNodeSetName(disp.geometry, mesh);

      // Write individual DOF constraints
      if (disp.displacement.x !== undefined) {
        this.lines.push(`${nodeSetName}, 1, 1, ${disp.displacement.x}`);
      }
      if (disp.displacement.y !== undefined) {
        this.lines.push(`${nodeSetName}, 2, 2, ${disp.displacement.y}`);
      }
      if (disp.displacement.z !== undefined) {
        this.lines.push(`${nodeSetName}, 3, 3, ${disp.displacement.z}`);
      }
    }
  }

  private writeLoad(bc: BoundaryCondition, mesh: FEAMesh | undefined): void {
    if (bc.type === 'force') {
      const force = bc as ForceLoad;
      const nodeSetName = this.getNodeSetName(force.geometry, mesh);
      const mag = force.force.magnitude;
      const dir = force.force.direction;

      // Calculate force components
      const fx = mag * dir.x;
      const fy = mag * dir.y;
      const fz = mag * dir.z;

      this.lines.push('*CLOAD');
      if (Math.abs(fx) > 1e-12) {
        this.lines.push(`${nodeSetName}, 1, ${fx.toExponential(8)}`);
      }
      if (Math.abs(fy) > 1e-12) {
        this.lines.push(`${nodeSetName}, 2, ${fy.toExponential(8)}`);
      }
      if (Math.abs(fz) > 1e-12) {
        this.lines.push(`${nodeSetName}, 3, ${fz.toExponential(8)}`);
      }
    } else if (bc.type === 'pressure') {
      const pressure = bc as PressureLoad;
      // For pressure, we need surface definition
      // Simplified: apply as distributed load
      this.lines.push('*DLOAD');
      this.lines.push(`Eall, P, ${pressure.pressure.toExponential(8)}`);
    } else if (bc.type === 'gravity') {
      const gravity = bc as GravityLoad;
      const dir = gravity.direction;

      this.lines.push('*DLOAD');
      // GRAV load: element_set, GRAV, magnitude, dir_x, dir_y, dir_z
      this.lines.push(
        `Eall, GRAV, ${gravity.acceleration.toExponential(8)}, ` +
          `${dir.x.toFixed(6)}, ${dir.y.toFixed(6)}, ${dir.z.toFixed(6)}`
      );
    }
  }

  private writeOutputRequests(): void {
    this.lines.push('**');
    this.lines.push('** OUTPUT REQUESTS');
    this.lines.push('**');

    // Nodal outputs (displacements)
    this.lines.push('*NODE FILE');
    this.lines.push('U');  // Displacements

    // Element outputs (stresses, strains)
    this.lines.push('*EL FILE');
    this.lines.push('S, E');  // Stresses and Strains

    // Additional print to .dat file
    this.lines.push('*NODE PRINT, NSET=Nall');
    this.lines.push('U');

    this.lines.push('*EL PRINT, ELSET=Eall');
    this.lines.push('S');
  }

  private getNodeSetName(
    geometry: { type: string; id: string; name?: string },
    mesh: FEAMesh | undefined
  ): string {
    // Try to find matching node set
    if (mesh && mesh.nodeSets) {
      // Look for a node set matching the geometry
      const matchingSet = mesh.nodeSets.find(
        (ns) =>
          ns.name === geometry.id ||
          ns.name === geometry.name ||
          ns.name.includes(geometry.id)
      );
      if (matchingSet) {
        return matchingSet.name;
      }
    }

    // Default to a placeholder that should be replaced
    // with actual node IDs during preprocessing
    return geometry.name || geometry.id || 'Nall';
  }

  private sanitizeName(name: string): string {
    // CalculiX material names should be alphanumeric with underscores
    return name
      .replace(/[^a-zA-Z0-9_]/g, '_')
      .replace(/__+/g, '_')
      .replace(/^_+|_+$/g, '')
      .substring(0, 80); // Max length
  }
}

export const inpWriter = new InpWriter();

