/**
 * CalculiX Input File Writer
 * Generates complete .inp files from FEA setup
 */

import type { FEMesh, SimulationSetup, BoundaryCondition, FEAMaterial } from '@feai/shared';

export class CalculiXInputWriter {
  /**
   * Generate complete CalculiX .inp file
   */
  static writeInput(mesh: FEMesh, setup: SimulationSetup): string {
    let inp = '';

    // Header
    inp += this.writeHeader(setup);

    // Nodes
    inp += this.writeNodes(mesh);

    // Elements
    inp += this.writeElements(mesh);

    // Materials
    inp += this.writeMaterials(setup);

    // Sections (link elements to materials)
    inp += this.writeSections(setup);

    // Analysis step
    inp += this.writeStep(setup);

    return inp;
  }

  private static writeHeader(setup: SimulationSetup): string {
    return `*HEADING
${setup.name || 'FEA Simulation'}
Generated by FEAI CAD System
Analysis Type: ${setup.analysisType}
*PREPRINT

`;
  }

  private static writeNodes(mesh: FEMesh): string {
    let inp = '*NODE\n';
    for (const node of mesh.nodes) {
      inp += `${node.id}, ${node.x.toFixed(6)}, ${node.y.toFixed(6)}, ${node.z.toFixed(6)}\n`;
    }
    inp += '\n';
    return inp;
  }

  private static writeElements(mesh: FEMesh): string {
    let inp = '';
    
    // Group elements by type
    const elementsByType = new Map<string, typeof mesh.elements>();
    for (const elem of mesh.elements) {
      const type = elem.type || 'C3D4';
      if (!elementsByType.has(type)) {
        elementsByType.set(type, []);
      }
      elementsByType.get(type)!.push(elem);
    }

    // Write each element type group
    for (const [type, elements] of elementsByType) {
      inp += `*ELEMENT, TYPE=${type}, ELSET=E${type}\n`;
      for (const elem of elements) {
        inp += `${elem.id}, ${elem.nodeIds.join(', ')}\n`;
      }
      inp += '\n';
    }

    // Create set of all elements
    inp += '*ELSET, ELSET=Eall\n';
    for (const type of elementsByType.keys()) {
      inp += `E${type}\n`;
    }
    inp += '\n';

    return inp;
  }

  private static writeMaterials(setup: SimulationSetup): string {
    let inp = '';

    // Get unique materials from assignments
    const materialsUsed = new Set<string>();
    for (const assignment of setup.materialAssignments || []) {
      materialsUsed.add(assignment.materialId);
    }

    // Write each material
    for (const matId of materialsUsed) {
      const material = setup.materials?.find(m => m.id === matId);
      if (material) {
        inp += this.writeMaterial(material);
      }
    }

    return inp;
  }

  private static writeMaterial(material: FEAMaterial): string {
    let inp = `*MATERIAL, NAME=${material.name || material.id}\n`;

    // Elastic properties
    const props = material.properties;
    if (props.youngsModulus && props.poissonsRatio !== undefined) {
      inp += '*ELASTIC\n';
      inp += `${props.youngsModulus}, ${props.poissonsRatio}\n`;
    }

    // Density (needed for dynamics/gravity)
    if (props.density) {
      inp += '*DENSITY\n';
      inp += `${props.density}\n`;
    }

    // Thermal expansion (if available)
    if (props.thermalExpansion) {
      inp += '*EXPANSION\n';
      inp += `${props.thermalExpansion}\n`;
    }

    inp += '\n';
    return inp;
  }

  private static writeSections(setup: SimulationSetup): string {
    let inp = '';

    // If no material assignments, assign default to all
    if (!setup.materialAssignments || setup.materialAssignments.length === 0) {
      const defaultMat = setup.materials?.[0];
      if (defaultMat) {
        inp += `*SOLID SECTION, ELSET=Eall, MATERIAL=${defaultMat.name || defaultMat.id}\n`;
        inp += '1.0\n\n';
      }
      return inp;
    }

    // Link each part to its material
    for (const assignment of setup.materialAssignments) {
      const material = setup.materials?.find(m => m.id === assignment.materialId);
      if (material) {
        // Use part name as element set (assuming mesh generator creates these)
        const elsetName = `E_${assignment.partId}`;
        inp += `*SOLID SECTION, ELSET=${elsetName}, MATERIAL=${material.name || material.id}\n`;
        inp += '1.0\n';
      }
    }

    inp += '\n';
    return inp;
  }

  private static writeStep(setup: SimulationSetup): string {
    let inp = '*STEP\n';

    // Write analysis type
    switch (setup.analysisType) {
      case 'static':
        inp += this.writeStaticAnalysis(setup);
        break;
      case 'modal':
        inp += this.writeModalAnalysis(setup);
        break;
      case 'buckling':
        inp += this.writeBucklingAnalysis(setup);
        break;
      case 'thermal':
        inp += this.writeThermalAnalysis(setup);
        break;
      case 'nonlinearStatic':
        inp += this.writeNonlinearStaticAnalysis(setup);
        break;
      default:
        inp += this.writeStaticAnalysis(setup);
    }

    inp += '*END STEP\n';
    return inp;
  }

  private static writeStaticAnalysis(setup: SimulationSetup): string {
    let inp = '*STATIC\n';

    // Boundary conditions
    inp += this.writeBoundaryConditions(setup.boundaryConditions || []);

    // Output requests
    inp += this.writeOutputRequests();

    return inp;
  }

  private static writeNonlinearStaticAnalysis(setup: SimulationSetup): string {
    let inp = '*STATIC, NLGEOM\n';
    inp += '0.1, 1.0\n'; // Initial increment, total time

    // Boundary conditions
    inp += this.writeBoundaryConditions(setup.boundaryConditions || []);

    // Output requests
    inp += this.writeOutputRequests();

    return inp;
  }

  private static writeModalAnalysis(setup: SimulationSetup): string {
    const numModes = (setup as any).numModes || 10;
    let inp = `*FREQUENCY\n${numModes}\n`;

    // No loads in modal (unless pre-stress)
    // Output requests
    inp += '*NODE FILE\n';
    inp += 'U\n';

    return inp;
  }

  private static writeBucklingAnalysis(setup: SimulationSetup): string {
    const numModes = (setup as any).numBucklingModes || 5;
    let inp = `*BUCKLE\n${numModes}\n`;

    // Boundary conditions (for preload)
    inp += this.writeBoundaryConditions(setup.boundaryConditions || []);

    inp += '*NODE FILE\n';
    inp += 'U\n';

    return inp;
  }

  private static writeThermalAnalysis(setup: SimulationSetup): string {
    let inp = '*HEAT TRANSFER, STEADY STATE\n';

    // Temperature boundary conditions
    inp += this.writeThermalBCs(setup.boundaryConditions || []);

    // Output requests
    inp += '*NODE FILE\n';
    inp += 'NT\n'; // Nodal temperatures

    return inp;
  }

  private static writeDynamicAnalysis(setup: SimulationSetup): string {
    const totalTime = (setup as any).totalTime || 1.0;
    const timeStep = (setup as any).timeStep || 0.01;
    
    let inp = '*DYNAMIC\n';
    inp += `${timeStep}, ${totalTime}\n`;

    // Boundary conditions
    inp += this.writeBoundaryConditions(setup.boundaryConditions || []);

    // Output requests
    inp += this.writeOutputRequests();

    return inp;
  }

  private static writeBoundaryConditions(bcs: BoundaryCondition[]): string {
    let inp = '';

    // Group BCs by type
    const fixedBCs: BoundaryCondition[] = [];
    const forceBCs: BoundaryCondition[] = [];
    const pressureBCs: BoundaryCondition[] = [];
    const displacementBCs: BoundaryCondition[] = [];

    for (const bc of bcs) {
      if (!bc.enabled) continue;
      
      switch (bc.type) {
        case 'fixed':
          fixedBCs.push(bc);
          break;
        case 'force':
          forceBCs.push(bc);
          break;
        case 'pressure':
          pressureBCs.push(bc);
          break;
        case 'displacement':
          displacementBCs.push(bc);
          break;
      }
    }

    // Write fixed supports
    if (fixedBCs.length > 0) {
      inp += '*BOUNDARY\n';
      for (const bc of fixedBCs) {
        // Get nodes from location (simplified - would need actual node selection)
        const nodeSet = this.getNodeSetName(bc);
        inp += `${nodeSet}, 1, 3, 0.0\n`;
      }
    }

    // Write prescribed displacements
    if (displacementBCs.length > 0) {
      inp += '*BOUNDARY\n';
      for (const bc of displacementBCs) {
        const nodeSet = this.getNodeSetName(bc);
        const disp = (bc as any).displacement || { x: 0, y: 0, z: 0 };
        if (disp.x !== 0) inp += `${nodeSet}, 1, 1, ${disp.x}\n`;
        if (disp.y !== 0) inp += `${nodeSet}, 2, 2, ${disp.y}\n`;
        if (disp.z !== 0) inp += `${nodeSet}, 3, 3, ${disp.z}\n`;
      }
    }

    // Write forces
    if (forceBCs.length > 0) {
      inp += '*CLOAD\n';
      for (const bc of forceBCs) {
        const nodeSet = this.getNodeSetName(bc);
        const force = (bc as any).force || { x: 0, y: 0, z: 0 };
        const magnitude = (bc as any).magnitude || 0;
        
        // Apply in specified direction (default Z)
        const dir = (bc as any).direction || 'z';
        const dof = dir === 'x' ? 1 : dir === 'y' ? 2 : 3;
        
        inp += `${nodeSet}, ${dof}, ${magnitude}\n`;
      }
    }

    // Write pressures
    if (pressureBCs.length > 0) {
      inp += '*DLOAD\n';
      for (const bc of pressureBCs) {
        const elset = this.getElementSetName(bc);
        const pressure = (bc as any).pressure || 0;
        const face = (bc as any).face || 'S1'; // Surface 1 by default
        
        inp += `${elset}, ${face}, ${pressure}\n`;
      }
    }

    return inp;
  }

  private static writeThermalBCs(bcs: BoundaryCondition[]): string {
    let inp = '';

    for (const bc of bcs) {
      if (!bc.enabled) continue;

      if (bc.type === 'temperature') {
        inp += '*BOUNDARY\n';
        const nodeSet = this.getNodeSetName(bc);
        const temp = (bc as any).temperature || 0;
        inp += `${nodeSet}, 11, 11, ${temp}\n`; // DOF 11 = temperature
      }
      // Note: heatFlux is also a valid BC type, but not in the structural union
      // We handle it with a type cast for thermal analysis
      if ((bc as any).type === 'heatFlux') {
        inp += '*DFLUX\n';
        const elset = this.getElementSetName(bc);
        const flux = (bc as any).flux || 0;
        inp += `${elset}, S, ${flux}\n`;
      }
    }

    return inp;
  }

  private static writeOutputRequests(): string {
    let inp = '';
    
    inp += '*NODE FILE\n';
    inp += 'U\n'; // Displacements
    
    inp += '*EL FILE\n';
    inp += 'S, E\n'; // Stress and strain
    
    return inp;
  }

  private static getNodeSetName(bc: BoundaryCondition): string {
    // In practice, this would map BC location to actual node set
    // For now, return a placeholder that should be defined in mesh
    return bc.id ? `NSET_${bc.id}` : 'NSET_1';
  }

  private static getElementSetName(bc: BoundaryCondition): string {
    // Map BC location to element set
    return bc.id ? `ESET_${bc.id}` : 'ESET_1';
  }
}
