/**
 * CalculiX FEA Compute Server
 * Runs CalculiX solver on dedicated compute instance
 */

import express from 'express';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import { spawn } from 'child_process';
import { writeFileSync, readFileSync, unlinkSync, existsSync, mkdirSync, rmSync } from 'fs';
import { join } from 'path';
import { v4 as uuidv4 } from 'uuid';
import { CalculiXInputWriter, CalculiXResultParser } from '@feai/kernel';
import type { FEMesh, SimulationSetup, FEAResults } from '@feai/shared';

const app = express();
const PORT = process.env.PORT || 3002;
const API_KEY = process.env.API_KEY || 'dev-key-change-in-production';
const TMP_DIR = process.env.TMP_DIR || '/tmp/fea-jobs';

// Ensure tmp directory exists
if (!existsSync(TMP_DIR)) {
  mkdirSync(TMP_DIR, { recursive: true });
}

// Middleware
app.use(cors());
app.use(express.json({ limit: '100mb' }));

// Request logging
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    const duration = Date.now() - start;
    console.log(`${new Date().toISOString()} ${req.method} ${req.path} ${res.statusCode} ${duration}ms`);
  });
  next();
});

// API Key authentication
app.use((req, res, next) => {
  // Skip auth for health check
  if (req.path === '/health') {
    return next();
  }

  const apiKey = req.headers['x-api-key'];
  if (apiKey !== API_KEY) {
    return res.status(401).json({
      success: false,
      error: {
        code: 'UNAUTHORIZED',
        message: 'Invalid API key',
      },
    });
  }
  next();
});

// Rate limiting
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 20, // 20 requests per window
  message: {
    success: false,
    error: {
      code: 'RATE_LIMIT',
      message: 'Too many solve requests. Please try again later.',
    },
  },
});

app.use('/solve', limiter);

// Health check
app.get('/health', (req, res) => {
  // Check if CalculiX is available
  const ccxAvailable = existsSync('/usr/local/bin/ccx');
  
  res.json({
    success: true,
    data: {
      status: 'healthy',
      solver: 'calculix',
      ccxAvailable,
      version: '1.0.0',
      timestamp: new Date().toISOString(),
    },
  });
});

// Solve FEA simulation
app.post('/solve', async (req, res) => {
  const { mesh, setup } = req.body as {
    mesh: FEMesh;
    setup: SimulationSetup;
  };

  if (!mesh || !setup) {
    return res.status(400).json({
      success: false,
      error: {
        code: 'INVALID_INPUT',
        message: 'mesh and setup are required',
      },
    });
  }

  const jobId = uuidv4();
  const jobDir = join(TMP_DIR, jobId);
  
  try {
    // Create job directory
    mkdirSync(jobDir, { recursive: true });

    const inputFile = join(jobDir, 'input.inp');
    const datFile = join(jobDir, 'input.dat');
    const frdFile = join(jobDir, 'input.frd');

    console.log(`[${jobId}] Starting FEA solve (${mesh.nodeCount} nodes, ${mesh.elementCount} elements)`);

    // Generate CalculiX input file
    const inpContent = CalculiXInputWriter.writeInput(mesh, setup);
    writeFileSync(inputFile, inpContent);

    console.log(`[${jobId}] Input file generated (${inpContent.length} bytes)`);

    // Run CalculiX solver
    const ccxProcess = spawn('ccx', ['-i', 'input'], {
      cwd: jobDir,
      timeout: 300000, // 5 minutes max
    });

    let stdout = '';
    let stderr = '';

    ccxProcess.stdout.on('data', (data) => {
      const text = data.toString();
      stdout += text;
      console.log(`[${jobId}] ${text.trim()}`);
    });

    ccxProcess.stderr.on('data', (data) => {
      const text = data.toString();
      stderr += text;
      console.error(`[${jobId}] ${text.trim()}`);
    });

    // Wait for process to complete
    await new Promise<void>((resolve, reject) => {
      ccxProcess.on('close', (code) => {
        if (code === 0) {
          resolve();
        } else {
          reject(new Error(`CalculiX exited with code ${code}`));
        }
      });

      ccxProcess.on('error', (error) => {
        reject(error);
      });
    });

    console.log(`[${jobId}] CalculiX completed successfully`);

    // Read output files
    const datContent = existsSync(datFile)
      ? readFileSync(datFile, 'utf-8')
      : '';

    const frdContent = existsSync(frdFile)
      ? readFileSync(frdFile, 'utf-8')
      : '';

    if (!frdContent) {
      throw new Error('No result file (.frd) generated by solver');
    }

    console.log(`[${jobId}] Parsing results...`);

    // Parse results
    const results: FEAResults = CalculiXResultParser.parseResults(frdContent, datContent);

    console.log(`[${jobId}] Results parsed successfully`);

    // Cleanup job directory
    try {
      unlinkSync(inputFile);
      unlinkSync(datFile);
      unlinkSync(frdFile);
      rmSync(jobDir, { recursive: true });
    } catch (cleanupError) {
      console.warn(`[${jobId}] Cleanup failed:`, cleanupError);
    }

    res.json({
      success: true,
      data: {
        jobId,
        results,
        log: datContent.substring(0, 10000), // Limit log size
        warnings: extractWarnings(datContent),
      },
    });

  } catch (error: any) {
    console.error(`[${jobId}] Solve failed:`, error);

    // Cleanup on error
    try {
      rmSync(jobDir, { recursive: true });
    } catch {}

    res.status(500).json({
      success: false,
      error: {
        code: 'SOLVE_FAILED',
        message: error.message || 'Simulation failed',
        details: error.stack,
      },
    });
  }
});

// Extract warnings from CalculiX log
function extractWarnings(datContent: string): string[] {
  const warnings: string[] = [];
  const lines = datContent.split('\n');
  
  for (const line of lines) {
    if (line.includes('*WARNING') || line.includes('WARNING:')) {
      warnings.push(line.trim());
    }
  }
  
  return warnings;
}

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('SIGTERM received, shutting down gracefully...');
  process.exit(0);
});

process.on('SIGINT', () => {
  console.log('SIGINT received, shutting down gracefully...');
  process.exit(0);
});

// Start server
app.listen(PORT, () => {
  console.log(`
╔═══════════════════════════════════════════════════════════╗
║          FEA Compute Server v1.0.0                        ║
╠═══════════════════════════════════════════════════════════╣
║  Endpoint:     http://localhost:${PORT}                      ║
║  Health:       http://localhost:${PORT}/health               ║
║  Solver:       CalculiX ccx 2.21                          ║
╠═══════════════════════════════════════════════════════════╣
║  Available Endpoints:                                     ║
║    POST /solve - Run FEA simulation                       ║
║    GET  /health - Health check                            ║
╚═══════════════════════════════════════════════════════════╝
  `);
});

export default app;

